version: "3.9"
services:
  postgres:
    container_name: dbConverterPostgres
    image: DB_ServiceStation
    environment:
      POSTGRES_DB: "DB_ServiceStation"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "8089:5432"
    #    healthcheck:
    #      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 5
    #      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#    networks:
#      - postgres
