version: "3.9"
services:
  deploy:
    depends_on:
      - postgres
    container_name: deployServiceStationProject
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbPostgres:5432/DB_ServiceStation
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
  postgres:
    container_name: dbPostgres
    image: postgres
    environment:
      POSTGRES_DB: "DB_ServiceStation"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "8089:5432"
    #    healthcheck:
    #      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 5
    #      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#    networks:
#      - postgres
